name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      
      
    - name: Set Up Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose


    - name: Build Binary
      run: cargo build --release -C target-cpu=x86_64-unknown-linux-gnu -C panic=abort --strip

    - name: Publish Binary
      uses: ncsoft/gh-action-github-release@v1.3.2
      with:
        tag_name: v${{ github.ref }}
        release_title: Release ${{ github.ref }}
        files: ./target/release/performant-markdown-to-wikilink
